name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]*'
  pull_request:

jobs:
    license-headers:
      name: Check licenses headers
      runs-on: ubuntu-latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v4
          with:
              persist-credentials: false
        - uses: actions/setup-node@v4
          with:
              node-version: 22
        - name: Check License Header (Check Mode)
          uses: apache/skywalking-eyes/header@v0.5.0
          with:
            config: .github/config/.licenserc.yaml

    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Parse tag
              id: vars
              run: echo ::set-output name=tag::${GITHUB_REF_NAME#v}

            - name: Install and Build
              run: |
                  npm ci
                  npm run licenses-check
                  npm run-script lint
                  npm run-script build
                  npm run-script test:coverage

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@v3.0.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: Build and publish Docker image - Main
              if: github.ref == 'refs/heads/main'
              uses: elgohr/Publish-Docker-Github-Action@33a481be3e179353cb7793a92b57cf9a6c985860 # v4
              with:
                  name: gridsuite/griddyna-app
                  username: gridsuiteci
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and publish Docker image - Tag
              if: startsWith(github.ref, 'refs/tags/')
              uses: elgohr/Publish-Docker-Github-Action@33a481be3e179353cb7793a92b57cf9a6c985860 # v4
              with:
                  name: gridsuite/griddyna-app
                  username: gridsuiteci
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
                  tags: ${{ steps.vars.outputs.tag }}

            - name: Broadcast update event
              if: github.ref == 'refs/heads/main'
              uses: gridsuite/broadcast-event@main
              with:
                  token: ${{ secrets.REPO_ACCESS_TOKEN }}
                  event-type: griddyna_app_updated
